In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Junayed\nyc-311-resolution-time-analysis\data\clean\311_jan_week1_clean.csv")

In [3]:
df.groupby("Agency")["Resolution_Days"].agg(
    Ticket_Count="count",
    Median="median",
    Mean="mean",
    P75=lambda x: x.quantile(0.75),
    P90=lambda x: x.quantile(0.90),
    Max='max'
).sort_values(by="Mean", ascending=False)

        Ticket_Count  Median        Mean     P75    P90  Max
Agency
EDC              452   138.0  138.701327  138.00  140.0  157
DOE               53    50.0  119.169811   78.00  496.0  496
TLC              526    73.0   64.155894   83.00  124.0  314
DOB             1558     5.0   62.266367   66.00  210.2  621
DPR              898     7.0   42.418708   41.00  147.0  622
DHS              355     2.0   19.242254    6.00  108.6  118
DOHMH           1237     2.0   17.924818   47.00   60.0  114
DCWP             291     2.0   13.625430   30.00   32.0  247
HPD            19787     1.0   11.225451    3.00   25.0  281
DOT             3472     1.0    9.827477    4.00    9.0  567
OTI                6     4.5    6.666667    7.75   14.5   21
DEP             2766     0.0    5.639913    3.00    7.0  561
DSNY            4674     1.0    4.062473    3.00   11.0  274
NYPD           49047     0.0    0.080739    0.00    0.0    7

In [4]:
# Filter for EDC, group by complaint type, and aggregate resolution days
EDC_df = df[df["Agency"] == "EDC"]

EDC_breakdown = (
   EDC_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of EDC's total volume
EDC_breakdown["Pct_of_EDC"] = (EDC_breakdown["Ticket_Count"] / len(EDC_df) * 100).round(2)
EDC_breakdown["Cumulative_Pct"] = EDC_breakdown["Pct_of_EDC"].cumsum().round(2)
EDC_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_EDC,Cumulative_Pct
Complaint_Type,,,,,,,,
Noise - Helicopter,452,138.0,138.701327,138.0,140.0,157,100.0,100.0

In [5]:
# exporting EDC's data
EDC_df.to_csv("EDC_Tickets.csv", index=False)
EDC_breakdown.to_csv("EDC_Complaints.csv", index=False)

In [6]:
# Filter for DOE, group by complaint type, and aggregate resolution days
DOE_df = df[df["Agency"] == "DOE"]

DOE_breakdown = (
   DOE_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DOE's total volume
DOE_breakdown["Pct_of_DOE"] = (DOE_breakdown["Ticket_Count"] / len(DOE_df) * 100).round(2)
DOE_breakdown["Cumulative_Pct"] = DOE_breakdown["Pct_of_DOE"].cumsum().round(2)
DOE_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DOE,Cumulative_Pct
Complaint_Type,,,,,,,,
School Maintenance,53,50.0,119.169811,78.0,496.0,496,100.0,100.0

In [7]:
# exporting DOE's data
DOE_df.to_csv("DOE_Tickets.csv", index=False)
DOE_breakdown.to_csv("DOE_Complaints.csv", index=False)

In [8]:
# Filter for TLC, group by complaint type, and aggregate resolution days
TLC_df = df[df["Agency"] == "TLC"]

TLC_breakdown = (
   TLC_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of TLC's total volume
TLC_breakdown["Pct_of_TLC"] = (TLC_breakdown["Ticket_Count"] / len(TLC_df) * 100).round(2)
TLC_breakdown["Cumulative_Pct"] = TLC_breakdown["Pct_of_TLC"].cumsum().round(2)
TLC_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_TLC,Cumulative_Pct
Complaint_Type,,,,,,,,
For Hire Vehicle Complaint,278,79.0,78.266187,85.00,127.5,294,52.85,52.85
Taxi Complaint,124,76.5,92.991935,106.50,147.6,314,23.57,76.42
Lost Property,120,0.0,0.591667,1.00,2.0,3,22.81,99.23
Green Taxi Complaint,4,96.5,96.500000,125.75,145.1,158,0.76,99.99

In [9]:
# exporting TLC's data
TLC_df.to_csv("TLC_Tickets.csv", index=False)
TLC_breakdown.to_csv("TLC_Complaints.csv", index=False)

In [10]:
# Filter for DOB, group by complaint type, and aggregate resolution days
DOB_df = df[df["Agency"] == "DOB"]

DOB_breakdown = (
   DOB_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DOB's total volume
DOB_breakdown["Pct_of_DOB"] = (DOB_breakdown["Ticket_Count"] / len(DOB_df) * 100).round(2)
DOB_breakdown["Cumulative_Pct"] = DOB_breakdown["Pct_of_DOB"].cumsum().round(2)
DOB_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DOB,Cumulative_Pct
Complaint_Type,,,,,,,,
General Construction/Plumbing,484,2.0,40.723140,40.00,138.7,621,31.07,31.07
Elevator,352,12.0,61.366477,105.75,183.6,360,22.59,53.66
Building/Use,285,63.0,121.603509,200.00,337.6,620,18.29,71.95
Real Time Enforcement,105,0.0,6.342857,0.00,2.0,373,6.74,78.69
Boilers,90,4.0,6.022222,7.00,13.2,32,5.78,84.47
Special Projects Inspection Team (Spit),77,101.0,224.025974,506.00,512.8,592,4.94,89.41
Emergency Response Team (Ert),55,4.0,6.163636,7.00,16.0,28,3.53,92.94
Plumbing,46,3.0,43.413043,45.75,138.0,576,2.95,95.89
Electrical,43,2.0,3.325581,5.00,7.0,13,2.76,98.65
Investigations And Discipline (Iad),15,2.0,7.066667,2.50,4.8,84,0.96,99.61

In [11]:
# exporting DOB's data
DOB_df.to_csv("DOB_Tickets.csv", index=False)
DOB_breakdown.to_csv("DOB_Complaints.csv", index=False)

In [12]:
# Filter for DPR, group by complaint type, and aggregate resolution days
DPR_df = df[df["Agency"] == "DPR"]

DPR_breakdown = (
   DPR_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DPR's total volume
DPR_breakdown["Pct_of_DPR"] = (DPR_breakdown["Ticket_Count"] / len(DPR_df) * 100).round(2)
DPR_breakdown["Cumulative_Pct"] = DPR_breakdown["Pct_of_DPR"].cumsum().round(2)
DPR_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DPR,Cumulative_Pct
Complaint_Type,,,,,,,,
Damaged Tree,239,2.0,15.066946,6.00,14.2,581,26.61,26.61
Maintenance Or Facility,191,9.0,48.910995,27.00,117.0,582,21.27,47.88
Root/Sewer/Sidewalk Condition,126,49.0,56.968254,63.00,91.0,413,14.03,61.91
Overgrown Tree/Branches,100,7.5,60.470000,101.75,160.5,495,11.14,73.05
Dead/Dying Tree,78,8.0,63.756410,19.50,195.1,622,8.69,81.74
Animal In A Park,65,0.0,3.153846,0.00,1.0,165,7.24,88.98
Illegal Tree Damage,40,9.0,32.075000,18.25,26.1,534,4.45,93.43
New Tree Request,30,147.0,148.233333,149.50,152.0,153,3.34,96.77
Violation Of Park Rules,19,0.0,0.000000,0.00,0.0,0,2.12,98.89
Wood Pile Remaining,8,11.0,83.125000,81.00,299.4,333,0.89,99.78

In [13]:
# exporting DPR's data
DPR_df.to_csv("DPR_Tickets.csv", index=False)
DPR_breakdown.to_csv("DPR_Complaints.csv", index=False)

In [14]:
# Filter for DHS, group by complaint type, and aggregate resolution days
DHS_df = df[df["Agency"] == "DHS"]

DHS_breakdown = (
   DHS_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DHS's total volume
DHS_breakdown["Pct_of_DHS"] = (DHS_breakdown["Ticket_Count"] / len(DHS_df) * 100).round(2)
DHS_breakdown["Cumulative_Pct"] = DHS_breakdown["Pct_of_DHS"].cumsum().round(2)
DHS_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DHS,Cumulative_Pct
Complaint_Type,,,,,,,,
Homeless Person Assistance,225,1.0,1.573333,3.00,5.0,6,63.38,63.38
Encampment,130,12.5,49.823077,109.75,115.0,118,36.62,100.00

In [15]:
# exporting DHS's data
DHS_df.to_csv("DHS_Tickets.csv", index=False)
DHS_breakdown.to_csv("DHS_Complaints.csv", index=False)

In [16]:
# Filter for DOHMH, group by complaint type, and aggregate resolution days
DOHMH_df = df[df["Agency"] == "DOHMH"]

DOHMH_breakdown = (
   DOHMH_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DOHMH's total volume
DOHMH_breakdown["Pct_of_DOHMH"] = (DOHMH_breakdown["Ticket_Count"] / len(DOHMH_df) * 100).round(2)
DOHMH_breakdown["Cumulative_Pct"] = DOHMH_breakdown["Pct_of_DOHMH"].cumsum().round(2)
DOHMH_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DOHMH,Cumulative_Pct
Complaint_Type,,,,,,,,
Rodent,450,0.0,0.657778,0.00,2.0,28,36.38,36.38
Food Establishment,199,60.0,41.276382,60.00,60.0,60,16.09,52.47
Indoor Air Quality,132,0.0,0.780303,0.00,2.0,48,10.67,63.14
Smoking Or Vaping,128,60.0,52.234375,60.00,60.0,60,10.35,73.49
Non-Residential Heat,84,60.0,53.976190,60.00,60.0,60,6.79,80.28
Mobile Food Vendor,67,8.0,22.313433,58.00,60.0,60,5.42,85.70
Food Poisoning,53,2.0,6.716981,11.00,17.8,54,4.28,89.98
Unsanitary Pigeon Condition,29,0.0,0.586207,0.00,1.2,9,2.34,92.32
Unsanitary Animal Pvt Property,26,0.0,0.423077,0.75,1.5,3,2.10,94.42
Day Care,15,3.0,4.266667,6.00,7.0,9,1.21,95.63

In [17]:
# exporting DOHMH's data
DOHMH_df.to_csv("DOHMH_Tickets.csv", index=False)
DOHMH_breakdown.to_csv("DOHMH_Complaints.csv", index=False)

In [18]:
# Filter for DCWP, group by complaint type, and aggregate resolution days
DCWP_df = df[df["Agency"] == "DCWP"]

DCWP_breakdown = (
   DCWP_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DCWP's total volume
DCWP_breakdown["Pct_of_DCWP"] = (DCWP_breakdown["Ticket_Count"] / len(DCWP_df) * 100).round(2)
DCWP_breakdown["Cumulative_Pct"] = DCWP_breakdown["Pct_of_DCWP"].cumsum().round(2)
DCWP_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DCWP,Cumulative_Pct
Complaint_Type,,,,,,,,
Consumer Complaint,291,2.0,13.62543,30.0,32.0,247,100.0,100.0

In [19]:
# exporting DCWP's data
DCWP_df.to_csv("DCWP_Tickets.csv", index=False)
DCWP_breakdown.to_csv("DCWP_Complaints.csv", index=False)

In [20]:
# Filter for HPD, group by complaint type, and aggregate resolution days
HPD_df = df[df["Agency"] == "HPD"]

HPD_breakdown = (
   HPD_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of HPD's total volume
HPD_breakdown["Pct_of_HPD"] = (HPD_breakdown["Ticket_Count"] / len(HPD_df) * 100).round(2)
HPD_breakdown["Cumulative_Pct"] = HPD_breakdown["Pct_of_HPD"].cumsum().round(2)
HPD_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_HPD,Cumulative_Pct
Complaint_Type,,,,,,,,
Heat/Hot Water,14711,1.0,1.162735,2.00,2.0,8,74.35,74.35
Unsanitary Condition,1273,20.0,43.468185,65.00,109.0,265,6.43,80.78
Plumbing,883,10.0,31.490374,37.00,92.8,279,4.46,85.24
Door/Window,578,19.0,44.847751,59.00,123.6,277,2.92,88.16
Paint/Plaster,523,9.0,32.571702,37.00,92.0,272,2.64,90.80
General,420,24.0,56.421429,79.00,173.4,269,2.12,92.92
Water Leak,417,14.0,39.354916,52.00,116.6,252,2.11,95.03
Electric,357,7.0,33.117647,42.00,115.6,272,1.80,96.83
Appliance,254,22.0,48.433071,73.75,132.1,252,1.28,98.11
Flooring/Stairs,232,18.5,41.431034,55.00,116.7,281,1.17,99.28

In [21]:
# exporting HPD's data
HPD_df.to_csv("HPD_Tickets.csv", index=False)
HPD_breakdown.to_csv("HPD_Complaints.csv", index=False)

In [22]:
# Filter for DOT, group by complaint type, and aggregate resolution days
DOT_df = df[df["Agency"] == "DOT"]

DOT_breakdown = (
   DOT_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DOT's total volume
DOT_breakdown["Pct_of_DOT"] = (DOT_breakdown["Ticket_Count"] / len(DOT_df) * 100).round(2)
DOT_breakdown["Cumulative_Pct"] = DOT_breakdown["Pct_of_DOT"].cumsum().round(2)
DOT_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DOT,Cumulative_Pct
Complaint_Type,,,,,,,,
Street Condition,1310,1.0,1.900763,1.00,2.0,367,37.73,37.73
Traffic Signal Condition,839,0.0,3.640048,0.00,2.0,380,24.16,61.89
Street Light Condition,459,6.0,32.854031,10.00,100.0,567,13.22,75.11
Sidewalk Condition,361,4.0,10.437673,7.00,9.0,390,10.40,85.51
Street Sign - Dangling,108,4.0,6.907407,7.00,9.0,225,3.11,88.62
Curb Condition,103,7.0,33.660194,45.50,111.2,222,2.97,91.59
Outdoor Dining,84,4.0,3.940476,5.00,7.7,10,2.42,94.01
Street Sign - Damaged,70,3.0,30.757143,9.00,80.3,356,2.02,96.03
Broken Parking Meter,46,4.0,10.913043,17.25,26.0,69,1.32,97.35
Street Sign - Missing,45,2.0,40.288889,7.00,131.4,366,1.30,98.65

In [23]:
# exporting DOT's data
DOT_df.to_csv("DOT_Tickets.csv", index=False)
DOT_breakdown.to_csv("DOT_Complaints.csv", index=False)

In [24]:
# Filter for OTI, group by complaint type, and aggregate resolution days
OTI_df = df[df["Agency"] == "OTI"]

OTI_breakdown = (
   OTI_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of OTI's total volume
OTI_breakdown["Pct_of_OTI"] = (OTI_breakdown["Ticket_Count"] / len(OTI_df) * 100).round(2)
OTI_breakdown["Cumulative_Pct"] = OTI_breakdown["Pct_of_OTI"].cumsum().round(2)
OTI_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_OTI,Cumulative_Pct
Complaint_Type,,,,,,,,
Linknyc,6,4.5,6.666667,7.75,14.5,21,100.0,100.0

In [25]:
# exporting OTI's data
OTI_df.to_csv("OTI_Tickets.csv", index=False)
OTI_breakdown.to_csv("OTI_Complaints.csv", index=False)

In [26]:
# Filter for DEP, group by complaint type, and aggregate resolution days
DEP_df = df[df["Agency"] == "DEP"]

DEP_breakdown = (
   DEP_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DEP's total volume
DEP_breakdown["Pct_of_DEP"] = (DEP_breakdown["Ticket_Count"] / len(DEP_df) * 100).round(2)
DEP_breakdown["Cumulative_Pct"] = DEP_breakdown["Pct_of_DEP"].cumsum().round(2)
DEP_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DEP,Cumulative_Pct
Complaint_Type,,,,,,,,
Water System,954,0.0,10.011530,2.0,20.0,561,34.49,34.49
Noise,879,2.0,3.207053,5.0,7.0,54,31.78,66.27
Lead,369,1.0,4.403794,3.0,3.0,85,13.34,79.61
Sewer,326,0.0,2.230061,0.0,3.0,335,11.79,91.40
Air Quality,118,1.0,1.593220,2.0,4.0,24,4.27,95.67
Water Conservation,43,0.0,1.093023,1.0,3.0,16,1.55,97.22
Water Quality,35,3.0,17.314286,11.5,73.2,81,1.27,98.49
Hazardous Materials,21,0.0,1.666667,0.0,0.0,35,0.76,99.25
Asbestos,11,0.0,0.090909,0.0,0.0,1,0.40,99.65
Industrial Waste,9,0.0,0.111111,0.0,0.2,1,0.33,99.98

In [27]:
# exporting DEP's data
DEP_df.to_csv("DEP_Tickets.csv", index=False)
DEP_breakdown.to_csv("DEP_Complaints.csv", index=False)

In [28]:
# Filter for DSNY, group by complaint type, and aggregate resolution days
DSNY_df = df[df["Agency"] == "DSNY"]

DSNY_breakdown = (
   DSNY_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of DSNY's total volume
DSNY_breakdown["Pct_of_DSNY"] = (DSNY_breakdown["Ticket_Count"] / len(DSNY_df) * 100).round(2)
DSNY_breakdown["Cumulative_Pct"] = DSNY_breakdown["Pct_of_DSNY"].cumsum().round(2)
DSNY_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_DSNY,Cumulative_Pct
Complaint_Type,,,,,,,,
Dirty Condition,932,0.0,0.844421,1.0,2.0,17,19.94,19.94
Derelict Vehicles,731,0.0,0.634747,1.0,2.0,11,15.64,35.58
Illegal Dumping,642,2.0,3.981308,5.0,11.0,31,13.74,49.32
Snow Or Ice,542,1.0,1.658672,2.0,5.0,18,11.60,60.92
Graffiti,324,35.0,30.064815,36.0,48.0,132,6.93,67.85
Residential Disposal Complaint,271,1.0,1.439114,1.5,4.0,11,5.80,73.65
Vendor Enforcement,258,0.0,0.000000,0.0,0.0,0,5.52,79.17
Obstruction,241,1.0,2.539419,4.0,10.0,14,5.16,84.33
Dead Animal,145,1.0,3.055172,4.0,10.0,23,3.10,87.43
Missed Collection,130,4.0,5.092308,7.0,13.0,30,2.78,90.21

In [29]:
# exporting DSNY's data
DSNY_df.to_csv("DSNY_Tickets.csv", index=False)
DSNY_breakdown.to_csv("DSNY_Complaints.csv", index=False)

In [30]:
# Filter for NYPD, group by complaint type, and aggregate resolution days
NYPD_df = df[df["Agency"] == "NYPD"]

NYPD_breakdown = (
   NYPD_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of NYPD's total volume
NYPD_breakdown["Pct_of_NYPD"] = (NYPD_breakdown["Ticket_Count"] / len(NYPD_df) * 100).round(2)
NYPD_breakdown["Cumulative_Pct"] = NYPD_breakdown["Pct_of_NYPD"].cumsum().round(2)
NYPD_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_NYPD,Cumulative_Pct
Complaint_Type,,,,,,,,
Noise - Residential,30224,0.0,0.121195,0.0,1.0,4,61.62,61.62
Illegal Parking,9745,0.0,0.014366,0.0,0.0,4,19.87,81.49
Blocked Driveway,3297,0.0,0.025174,0.0,0.0,5,6.72,88.21
Abandoned Vehicle,1195,0.0,0.040167,0.0,0.0,7,2.44,90.65
Noise - Commercial,1058,0.0,0.001890,0.0,0.0,2,2.16,92.81
Noise - Street/Sidewalk,1054,0.0,0.000949,0.0,0.0,1,2.15,94.96
Noise - Vehicle,472,0.0,0.010593,0.0,0.0,2,0.96,95.92
Non-Emergency Police Matter,386,0.0,0.007772,0.0,0.0,2,0.79,96.71
Drug Activity,371,0.0,0.008086,0.0,0.0,2,0.76,97.47
Encampment,321,0.0,0.006231,0.0,0.0,1,0.65,98.12

In [31]:
# exporting NYPD's data
NYPD_df.to_csv("NYPD_Tickets.csv", index=False)
NYPD_breakdown.to_csv("NYPD_Complaints.csv", index=False)