In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Junayed\nyc-311-resolution-time-analysis\data\clean\311_jan_week1_clean.csv")

In [4]:
df.groupby("Agency")["Resolution_Days"].agg(
    Ticket_Count="count",
    Median="median",
    Mean="mean",
    P75=lambda x: x.quantile(0.75),
    P90=lambda x: x.quantile(0.90),
    Max='max'
).sort_values(by="Mean", ascending=False)

        Ticket_Count  Median        Mean     P75    P90  Max
Agency
EDC              452   138.0  138.701327  138.00  140.0  157
DOE               53    50.0  119.169811   78.00  496.0  496
TLC              526    73.0   64.155894   83.00  124.0  314
DOB             1558     5.0   62.266367   66.00  210.2  621
DPR              898     7.0   42.418708   41.00  147.0  622
DHS              355     2.0   19.242254    6.00  108.6  118
DOHMH           1237     2.0   17.924818   47.00   60.0  114
DCWP             291     2.0   13.625430   30.00   32.0  247
HPD            19787     1.0   11.225451    3.00   25.0  281
DOT             3472     1.0    9.827477    4.00    9.0  567
OTI                6     4.5    6.666667    7.75   14.5   21
DEP             2766     0.0    5.639913    3.00    7.0  561
DSNY            4674     1.0    4.062473    3.00   11.0  274
NYPD           49047     0.0    0.080739    0.00    0.0    7

In [9]:
# Filter for EDC, group by complaint type, and aggregate resolution days
EDC_df = df[df["Agency"] == "EDC"]

EDC_breakdown = (
   EDC_df.groupby("Complaint_Type")["Resolution_Days"]
    .agg(
        Ticket_Count="count",
        Median="median",
        Mean="mean",
        P75=lambda x: x.quantile(0.75),
        P90=lambda x: x.quantile(0.90),
        Max="max",
    )
    .sort_values(by="Ticket_Count", ascending=False)
)

# Add category percentage of EDC's total volume
EDC_breakdown["Pct_of_EDC"] = (EDC_breakdown["Ticket_Count"] / len(EDC_df) * 100).round(2)
EDC_breakdown["Cumulative_Pct"] = EDC_breakdown["Pct_of_EDC"].cumsum().round(2)
EDC_breakdown.head(10)

,Ticket_Count,Median,Mean,P75,P90,Max,Pct_of_EDC,Cumulative_Pct
Complaint_Type,,,,,,,,
Noise - Helicopter,452,138.0,138.701327,138.0,140.0,157,100.0,100.0

In [11]:
# exporting EDC's data
EDC_df.to_csv("EDC_Tickets.csv", index=False)
EDC_breakdown.to_csv("EDC_Complaints.csv", index=False)